package main

import (
	"fmt"

	"github.com/pkg/errors"
)

func fn() (i int, err autoerr) {
	a, err := func(args) (err autoerr) {
		b, err := B()
		if err != nil {
			err = errors.Wrap(err, "fn `[anonymous_fn]` failed at a.go:5 when invoking `B`")
			return
		}

	}(args)
	if err != nil {
		err = errors.Wrap(err, "fn `fn` failed at a.go:6 when invoking `[anonymous_fn]`"+fmt.Sprintf(" with arg0 = %v; ", args))
		return
	}

}
